production:
  channels: &production_channels
    - uibcdf/label/dev
    - uibcdf
    - conda-forge
    - ambermd
  dependencies: &production_dependencies
    - python
    - numpy
    - openmm
    - jupyterlab
    - matplotlib

docs:
  channels: &docs_channels
    - *production_channels
  dependencies: &docs_dependencies
    - *production_dependencies
    - sphinx
    - sphinx_rtd_theme
    - sphinxcontrib-bibtex
    - nbsphinx
    - recommonmark
    - sphinx-markdown-tables

development:
  channels:
    - *production_channels
  dependencies:
    - *production_dependencies
    - *docs_dependencies

